#!/usr/bin/env python
#not checking the validity of input data


print('Simple Calculator')

number1 = int(input("Enter the first number: "))

operator = input("type A for addition, M for multiplication, D for Division, S for Subtraction: ").upper()

number2 = int(input("Enter the second number: "))


if operator == "A":
    print(f"{number1} + {number2} = {number1 + number2}")
elif operator == "M":
    print(f"{number1} x {number2} = {number1 * number2}")
elif operator == "D":
    print(f"{number1} / {number2} = {number1 / number2}")
elif operator == "S":
    print(f"{number1} - {number2} = {number1 - number2}")
else:
    print("Unacceptable or invalid numbers or operator")
